name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclencher l'action à chaque push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build  # Lancer la commande de build pour ton projet

      - name: Deploy to GitHub Pages
        run: |
          echo "const TOKEN = '${{ secrets.GITHUB_TOKEN }}';" >> .env  # Ajouter le token dans un fichier .env
          
      - name: Deploy to GitHub Pages
        run: |
          # Lancer le déploiement, en fonction de ta configuration (par exemple, avec gh-pages)
          npm run deploy
