name: Update Data on GitHub

on:
  workflow_dispatch:  # Permet de déclencher manuellement ou via une API

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq (JSON parser)
        run: sudo apt-get install jq

      - name: Add new word entry
        run: |
          # Variables pour les nouvelles données
          WORD="${{ github.event.inputs.word }}"
          TRANSLATION="${{ github.event.inputs.translation }}"
          USAGE="${{ github.event.inputs.usage }}"

          # Télécharger le fichier actuel
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://raw.githubusercontent.com/${{ github.repository }}/main/data/words.json" \
            -o words.json

          # Ajouter les nouvelles données
          jq ". + [{\"word\": \"$WORD\", \"translation\": \"$TRANSLATION\", \"usage\": \"$USAGE\"}]" words.json > updated_words.json

          # Commit et push des données mises à jour
          mv updated_words.json words.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update words.json with new word"
          git push
