name: Update Words Data

on:
  workflow_dispatch:
    inputs:
      word:
        description: "Mot à ajouter"
        required: true
      translation:
        description: "Traduction"
        required: true
      usage:
        description: "Usage"
        required: true

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      # Vérifier les entrées reçues
      - name: Vérifier les entrées
        run: |
          echo "Mot: ${{ github.event.inputs.word }}"
          echo "Traduction: ${{ github.event.inputs.translation }}"
          echo "Usage: ${{ github.event.inputs.usage }}"

      # Télécharger le fichier JSON actuel
      - name: Télécharger le fichier JSON actuel
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://raw.githubusercontent.com/${{ github.repository }}/main/data/words.json" \
            -o words.json

          echo "Contenu avant mise à jour :"
          cat words.json

      # Ajouter les nouvelles données
      - name: Ajouter les nouvelles données
        run: |
          WORD="${{ github.event.inputs.word }}"
          TRANSLATION="${{ github.event.inputs.translation }}"
          USAGE="${{ github.event.inputs.usage }}"

          jq ". + [{\"word\": \"$WORD\", \"translation\": \"$TRANSLATION\", \"usage\": \"$USAGE\"}]" words.json > updated_words.json

          echo "Contenu après mise à jour :"
          cat updated_words.json

      # Commit et push les modifications
      - name: Commit et pousser les modifications
        run: |
          mv updated_words.json words.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add words.json
          git commit -m "Mise à jour du fichier words.json" || echo "Aucun changement détecté."
          git push
